[project]
name = 'Virtual-Pet-Ecosystem'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.competition]
path = 'contracts/competition.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
